"Geo Data Science with Python" 
### Notebook Exercise 7a

# Matrix and Vector Operations


### Tutorial 2

Now, measure the runtime for matrix multiplication numpy (linear algepra multiplication) and compare it to that of an algorithm using for-loops. For that, find code for algorithm using for-loops in the function `matrixMultiplication`, given in the script `matrixMultiplication.py`. The script also defines two test matrices A and B.

What is the runtime for the loop-algorithm compared to numpy multiplication of the two matrices A and B?

Explain why the calculation of one algorithm is faster than the other one!

In [1]:
import numpy as np

In [2]:
# naive implementation
def matrixMultiplication(A, B):
    """
    Do not use this one because it is too slow.
    """
    assert A.shape[1] == B.shape[0]
    numRow, numCol = A.shape[0], B.shape[1]
    commonDim = A.shape[1] # B.shape[0]
    
    C = np.zeros((numRow, numCol))
    for i in range(numRow):
        for j in range(numCol):
            for k in range(commonDim):
                C[i][j] += A[i][k] * B[k][j]
    return C

#%%        
A = np.array([
              [1, 2],
              [3, 4],
              [5, 6]])
B = np.array([
              [11, 12],
              [13, 14]
             ])



In [3]:
# timing the loop algorithm
%timeit matrixMultiplication(A,B)

# matrixMultiplication(A,B)

19.4 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
# timing the numpy operation 
%timeit A @ B

# A @ B

1.45 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


##### Answer:

> The loop-algorithm linearly performs the required multiplication, one value at a time. The numpy multiplication performs the calculation on an entire set of values in one go, hence vectorisation. The result here is that the numpy calculation is at least one order of magnitude faster than the loop algorithm.

### NumPy Matrix
Matrix data type in numpy is available as alternative currently, but it be deprecated eventually.

In [5]:
# matrix class of numpy is a subclass of ndarray
npMatrix = np.matrix('1 2 3; 4 5 6')
npMatrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
type(npMatrix)

numpy.matrix

More details in the references: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

And a discussion on when to use array versus matrix: https://numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use

## Rules of Broadcasting
Let's get continue with NumPy arrays. 
When combining arrays of different sizes for matrix summation, substraction and element-by matrix multipliation with `*` or `np.multiply()`, rules of broadcasting will be applied.

**Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

**Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

These rules apply, for example, when multiplying or adding a scalar to a vector or a matrix.

In [7]:
matrix = np.array([  [1, 2, 3],
                     [4, 5, 6]   ])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
vector = np.array([  [10, 10, 10]  ])
vector

array([[10, 10, 10]])

In [9]:
scalar = np.array([100]) 
scalar

array([100])

In [10]:
matrix + scalar

array([[101, 102, 103],
       [104, 105, 106]])

In [11]:
vector + scalar

array([[110, 110, 110]])

These rules also apply, when multiply or sum a vector to a matrix.

In [12]:
matrix + vector

array([[11, 12, 13],
       [14, 15, 16]])

### Special Matrices

Let's get continue with NumPy arrays and define some special matrices with them.

In [13]:
# Diagonal matrix
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [14]:
# Identity matrix
np.identity(10)
# or
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
# Inverse matrix
# We will talk about this in a future class,
# as matrix inversion requires sophisticated operations
# np.linalg.inv works only for square matrices
A = np.array([[1, 2, 3], [1, 3, 3], [1, 2, 4]])
Ainv = np.linalg.inv(A)
Ainv

array([[ 6., -2., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

In [16]:
# A*A^-1 = I
A @Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Linear System of Equations

Linear equations like:

- $A_{11} x_1 + A_{12} x_2 + A_{13} x_3 = b_1$
- $A_{21} x_1 + A_{22} x_2 + A_{23} x_3 = b_2$
- $A_{31} x_1 + A_{32} x_2 + A_{33} x_3 = b_3$

... can be written in the form Ax = b.

In [17]:
# We can store the equation system in the matrix A, for example:
A = np.array([[1, 2, 3], [1, 3, 3], [1, 2, 4]])
A

array([[1, 2, 3],
       [1, 3, 3],
       [1, 2, 4]])

In [18]:
# Assume we have a set of parameter (independent variables),
# these are stored in the vector x:
x = np.array([[2,4,1]]).T

In [19]:
# The dependent variables can then be calculated and stored in the vector b:
b = A@x
b


array([[13],
       [17],
       [14]])

Our equation system looks like this:

- $x_1 + 2 x_2 + 3 x_3 = 13$
- $x_1 + 3 x_2 + 3 x_3 = 17$
- $x_1 + 2 x_2 + 4 x_3 = 14$

Now assume, **b** are observations, and **A** contains a geophysical model connecting model parameter **x** to observations **b**. We can then solve for x with the equation: $x = A^{-1}b$

In [20]:
# An inversion of the matrix A
Ainv = np.linalg.inv(A)

In [21]:
# ... can be used to calculate a solution of x, if we have b given:
x_calculated = Ainv@b
x_calculated

array([[2.],
       [4.],
       [1.]])

As you can see, the results for `x_calculated` are equal to the originally given parameter x above.